mysite/blog/urls.py
from django.urls import include, path
from . import views


app_name='blog'
urlpatterns = [
    #ex: /blog/
    path('', views.index,name='index'),
    #ex:/blog/1
    path('<int:posts_id>/',views.detail, name='detail')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
]

mysite/blog/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=100)
    snippet = models.CharField(max_length=200)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
# Create your views here.

def index(request):
    posts=Post.objects.all()
    context={
        'posts':posts,
    }
    return render(request, 'blog/index.html',context)

def detail(request,posts_id):
    post = get_object_or_404(Post, pk= posts_id)
    return render(request, 'blog/detail.html',{'post':post})
   

mysite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    <!-- <meta http-equiv="X-UA-Compatible" content="ie=edge"> -->

    <!-- bootstrap link-->
    

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
    
    <title>Document</title>
</head>
<body>
        <header class="site-header">
                <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                  <div class="container">
                    <a class="navbar-brand mr-4" href="{% url 'blog:index' %}">Django Blog</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                      <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'blog:index' %}">Home</a>
                        {% comment %} <a class="nav-item nav-link" href="{% url 'blog:detail' %}">About</a> {% endcomment %}
                      </div>
                      <!-- Navbar Right Side -->
                      <div class="navbar-nav">
                        <a class="nav-item nav-link" href="#">Login</a>
                        <a class="nav-item nav-link" href="#">Register</a>
                      </div>
                    </div>
                  </div>
                </nav>
              </header>
            
            <main role="main" class="container">
                    <div class="row">
                    <div class="col-md-8">
                        {% block content %}{% endblock %}
                    </div>
                    {% comment %} <div class="col-md-4">
                        <div class="content-section">
                        <h3>Our Sidebar</h3>
                        <p class='text-muted'>You can put any information here you'd like.
                            <ul class="list-group">
                            <li class="list-group-item list-group-item-light">Latest Posts</li>
                            <li class="list-group-item list-group-item-light">Announcements</li>
                            <li class="list-group-item list-group-item-light">Calendars</li>
                            <li class="list-group-item list-group-item-light">etc</li>
                            </ul>
                        </p>
                        </div>
                    </div> {% endcomment %}
                    </div>
                </main>
       
    

    <!-- scripts of js-->
        

</body>
</html>

mysite/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}

            <h1>{{post.title}}</h1>
            <p>{{post.author}}
            {{post.date_posted}}
            </p>
            <p>{{post.content}}</p>

{% endblock %}

mysite/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
    
    {% for post in posts %}
    <article class="media content-section">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="#">{{ post.author }}</a>
                <small class="text-muted">{{ post.date_posted }}</small>
              </div>
              <h2><a class="article-title" href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h2>
              <p class="article-content">{{ post.snippet }}</p>
            </div>
    </article>
          
    {% endfor %}
{% endblock content %}